=== UO270734/TopGun/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta  (nombre, tipo, transporte, fecha?, hora?, duracion, agencia, descripcion, personasAdecuadas, 
    lugarInicio, direccionInicio, coordenadas, referencia+, recomendacion, hito+, kml, svg)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT transporte (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personasAdecuadas (#PCDATA)>
<!ELEMENT lugarInicio (#PCDATA)>
<!ELEMENT direccionInicio (#PCDATA)>
<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hito (nombre, descripcion, coordenadas, distanciaAnterior, foto+, video*)>
<!ELEMENT distanciaAnterior (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT kml (#PCDATA)>
<!ELEMENT svg (#PCDATA)>
<!ATTLIST distanciaAnterior unidades CDATA #REQUIRED>
<!ATTLIST rutas
    xmlns:xsi CDATA #IMPLIED
    xsi:schemaLocation CDATA #IMPLIED
>

=== UO270734/TopGun/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
    <ruta>
        <nombre>Ruta del Agua de Chelva</nombre>
        <tipo>Paisajística</tipo>
        <transporte>A pie</transporte>
        <duracion>2 horas</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>La Ruta del Agua combina naturaleza y cultura en un agradable paseo de aproximadamente dos horas de duración con áreas de descanso, ideal para un público familiar.</descripcion>
        <personasAdecuadas>Todas las edades</personasAdecuadas>
        <lugarInicio>Plaza mayor de Chelva</lugarInicio>
        <direccionInicio>Pl. Mayor, 46176 Chelva, Valencia</direccionInicio>            
        <coordenadas>
            <longitud>39.747469</longitud>
            <latitud>-0.997671</latitud>            
            <altitud>482</altitud>
        </coordenadas>
        <referencia>https://www.chelva.es/page/ruta-del-agua</referencia>
        <referencia>https://www.turismochelva.es/quehacer/ruta-del-agua/</referencia>
        <referencia>https://es.wikiloc.com/rutas-senderismo/ruta-del-agua-de-chelva-la-playeta-tuneles-y-presa-de-olinches-fabrica-de-la-luz-54593042</referencia>
        <recomendacion>8</recomendacion>
		<hito>
            <nombre>Molino Puerto</nombre>
            <descripcion>Área recreativa por la que se debe pasar 2 veces, una a la ida y otra a la vuelta. Cuenta con un parking por si se desea dejar el coche en él.</descripcion>
            <coordenadas>
                <longitud>39.746117</longitud>
                <latitud>-1.005798</latitud>                
                <altitud>411</altitud>
            </coordenadas>
            <distanciaAnterior unidades="km">1</distanciaAnterior>
            <foto>molino_puerto.jpg</foto>
        </hito>
        <hito>
            <nombre>La Playeta</nombre>
            <descripcion>La Playeta es un paraje singular del río de Chelva, cuyas cascadas y remanso se convierten en una zona tradicional de baño que recibe su nombre de la arena de arrastre acumulada en la orilla.</descripcion>
            <coordenadas>
                <longitud>39.747452</longitud>
                <latitud>-1.009430</latitud>                
                <altitud>434</altitud>
            </coordenadas>
            <distanciaAnterior unidades="km">0.65</distanciaAnterior>
            <foto>la_playeta.jpg</foto>
        </hito>
        <hito>
            <nombre>Antigua presa de Olinches</nombre>
            <descripcion>En la antigua presa de Olinches se encuentra un área de descanso desde la que se pueden ver las compuertas que regulavan el caudal del río.</descripcion>
            <coordenadas>
                <longitud>39.745381</longitud>
                <latitud>-1.014719</latitud>                
                <altitud>604</altitud>
            </coordenadas>
            <distanciaAnterior unidades="km">2</distanciaAnterior>
            <foto>presa_olinches.jpg</foto>
            <video>https://www.youtube.com/watch?v=KO46oUs5mpo</video>
        </hito>
    </ruta>
    <ruta>
        <nombre>Cuevas de Badami</nombre>
        <tipo>Espeleología</tipo>
        <transporte>A pie</transporte>
        <duracion>2 horas</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Sendero que cubre las 4 principales cuevas de Badami, siendo estas patrimonio de la UNESCO. Sus tallas y esculturas datan del siglo VI.</descripcion>
        <personasAdecuadas>No recomendable para claustrofóbicos</personasAdecuadas>
        <lugarInicio>Aparcamiento de las cuevas de Badami</lugarInicio>
        <direccionInicio>WM9M+9GV, Badami Slums, Badami, Karnataka 587201, India</direccionInicio>            
        <coordenadas>
            <longitud>75.6840557</longitud>
            <latitud>15.9185856</latitud>            
            <altitud>576</altitud>
        </coordenadas>
        <referencia>Referencia 1: https://es.wikiloc.com/rutas-a-pie/badami-sightseeing-27765811</referencia>
        <referencia>Referencia 2: https://en.wikipedia.org/wiki/Badami_cave_temples</referencia>
        <referencia>Referencia 3: https://www.hisour.com/es/badami-cave-temples-27696/</referencia>
        <recomendacion>8</recomendacion>
        <hito>
            <nombre>Cueva 1</nombre>
            <descripcion>La cueva 1 se encuentra en la parte noroeste de la colina. 
            El acceso se realiza a través una escalera con tallas de "ganas" enanas en diferentes posturas como si sujetaran el suelo de la cueva. 
            La galería tiene cinco columnas esculpidas con relieves de guirnaldas de flores, follaje y joyas.</descripcion>
            <coordenadas>
                <longitud>75.68382516707194</longitud> 
                <latitud>15.918278164024052</latitud>                
                <altitud>580</altitud>
            </coordenadas>
            <distanciaAnterior unidades="m">26.35</distanciaAnterior>
            <foto>Entrada a la cueva 1: india_badami_cueva1.jpg</foto>
        </hito>
        <hito>
            <nombre>Cueva 2</nombre>
            <descripcion>La cueva 2 fue creada a finales del siglo VI o principios del VII. Es más pequeña que la Cueva 1 y está dedicada principalmente a Vishnu. 
            Se accede subiendo 64 escalones desde la primera cueva. La entrada está dividida por cuatro pilares cuadrados, tallados decorativamente con frisos
            de "ganas" con diversas expresiones faciales. A ambos lados de la entrada hay "dvarapalas" que sostienen flores. 
            Al igual que la Cueva 1, el arte de la Cueva 2 refleja la teología y las artes hindúes.</descripcion>
            <coordenadas>
                <longitud>75.68458860340502</longitud>
                <latitud>15.918259009540542</latitud>                
                <altitud>605</altitud>
            </coordenadas>
            <distanciaAnterior unidades="m">72.32</distanciaAnterior>
            <foto>Talla cueva 2: india_badami_cueva2.jpg</foto>
        </hito>
        <hito>
            <nombre>Cueva 3</nombre>
            <descripcion>La cueva 3 es el templo hindú más antiguo de la región de Deccan. Está dedicado a Vishnu y es la cueva más grande del complejo. 
                Tiene frisos intrincadamente tallados y figuras gigantes de Trivikrama, Anantasayana, Vasudeva, Varaha, Harihara y Narasimha. 
                El tema principal de la Cueva 3 es Vaishnavita, aunque también muestra a Harihara en su pared sur: la mitad Vishnu y la mitad Shiva se 
                muestran fusionadas como una sola, lo que hace que la cueva sea importante para los estudios del Shaivismo.</descripcion>
            <coordenadas>
                <longitud>75.68507712175435</longitud>
                <latitud>15.91829897179927</latitud>                
                <altitud>610</altitud>
            </coordenadas>
            <distanciaAnterior unidades="m">40.28</distanciaAnterior>
            <foto>Talla cueva 3: india_badami_cueva3.jpg</foto>
        </hito>
        <hito>
            <nombre>Cueva 4</nombre>
            <descripcion>La cueva 4 se ubica al este de la cueva 3, siendo la más pequeña de las cuatro. Está dedicada a las Tirthankaras, 
                las figuras veneradas del Jainismo. Fue construido después de las otras tres cuevas, patrocinada por reyes hindúes a finales del siglo VII. 
                Es probable que se le agregaran adornos en siglos posteriores hasta el siglo XI o XII, aproximadamente.</descripcion>
            <coordenadas>
                <longitud>75.6852626986023</longitud>
                <latitud>15.91817771575732</latitud>                
                <altitud>617</altitud>
            </coordenadas>
            <distanciaAnterior unidades="m">35.76</distanciaAnterior>
            <foto>Talla cueva 4: india_badami_cueva4.jpg</foto>
        </hito>
    </ruta>
    <ruta>
        <nombre>Etapa Chandigarh-Solan</nombre>
        <tipo>Cicloturismo</tipo>
        <transporte>Bicicleta</transporte>
        <duracion>6 horas</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>La ruta comienza en Chandigarh y termina en Solan, atravesando los estados de Himachal Pradesh y el Ladakh, en Jammu y Kashmir.
            Transcurre por diversos puertos de montaña, en los que se advierte de malas condiciones del terreno y asfalto.
            Se recomienda equipaje reducido con lo básico para alimentación, higiene y muda de ropa; para aligerar peso.
        </descripcion>
        <personasAdecuadas>Personas en buena forma física</personasAdecuadas>
        <lugarInicio>Hotel KC Residency, Chandigarh, India</lugarInicio>
        <direccionInicio>377-380, Himalaya Marg, 35C, Sector 35, Chandigarh, 160022, India</direccionInicio>            
        <coordenadas>
            <longitud>76.76287611980975</longitud>
            <latitud>30.723466915637356</latitud>            
            <altitud>337</altitud>
        </coordenadas>
        <referencia>Referencia 1: https://es.wikiloc.com/rutas-cicloturismo/chandigarh-leh-etapa-1-chandigarh-solan-23-jun-2013-4908464</referencia>
        <referencia>Referencia 2: </referencia>
        <referencia>Referencia 3: </referencia>
        <recomendacion>6</recomendacion>
        <hito>
            <nombre>Pinjore</nombre>
            <descripcion>La primera ciudad por la que pasa la ruta tras la salida de Chandigarh es Pinjore, aunque se atraviesan varios pueblos previamente.
                No es necesario adentrarse puesto que la carretera bordea la ciudad pero puede hacerse, si así se desea.</descripcion>
            <coordenadas>
                <longitud>76.91610715555137</longitud>
                <latitud>30.789683149988637</latitud>                
                <altitud>516</altitud>
            </coordenadas>
            <distanciaAnterior unidades="km">23.5</distanciaAnterior>
            <foto>Templo a la entrada de la ciudad de Pinjore: india_bici_pinjore.jpg</foto>
        </hito>
